name: Accessibility
on:
  pull_request:
    branches: [master]
    paths:
      - 'lighthouserc.js'
      - '.github/workflows/verify_accessibility.yml'
      - 'plugins/catalog/src/**'
      - 'plugins/catalog-react/src/**'
      - 'plugins/techdocs/src/**'
      - 'plugins/techdocs-react/src/**'
      - 'plugins/scaffolder/src/**'
      - 'plugins/scaffolder-react/src/**'
      - 'plugins/search/src/**'
      - 'plugins/search-react/src/**'

jobs:
  lhci:
    name: Accessibility
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.10.4
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Check if server is reachable
        run: curl -I http://localhost:3000 || echo "Server not reachable"

      - name: Run Lighthouse CI
        run: yarn dlx @lhci/cli@0.11.x autorun
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print LHCI logs
        run: cat .lighthouseci/*log* || echo "No LHCI logs found"

      - name: List Lighthouse Report Files
        run: ls -l ./.lighthouseci/reports || echo "No report directory found"

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./.lighthouseci/reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
